apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elearning.fullname" . }}-course-service-config
  labels:
    {{- include "elearning.courseService.labels" . | nindent 4 }}
data:
  config.yaml: |
    port: {{ .Values.courseService.service.port }}
    jwt_expiry_hours: {{ .Values.courseService.env.JWT_EXPIRY_HOURS }}
    cors_origins:
      - "{{ include "elearning.publicUrl" . }}"
    uploads_dir: "/data/uploads"
    k8s_namespace: {{ .Release.Namespace | quote }}
    user_service_url: "http://{{ include "elearning.fullname" . }}-user-service.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.userService.service.port }}"
    git_cache_ttl_minutes: {{ .Values.courseService.env.GIT_CACHE_TTL }}
    git_credentials_path: "/etc/git-credentials/git-credentials.yaml"
    checker_service_url: "http://{{ include "elearning.fullname" . }}-checker-service.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.checkerService.service.port }}"
