apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pupitre.fullname" . }}-course-service-config
  labels:
    {{- include "pupitre.courseService.labels" . | nindent 4 }}
data:
  config.yaml: |
    port: {{ .Values.courseService.service.port }}
    jwtExpiryHours: {{ .Values.courseService.env.JWT_EXPIRY_HOURS }}
    corsOrigins:
      - "{{ include "pupitre.publicUrl" . }}"
    uploadsDir: "/data/uploads"
    k8sNamespace: {{ .Release.Namespace | quote }}
    userServiceUrl: "http://{{ include "pupitre.fullname" . }}-user-service.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.userService.service.port }}"
    gitCacheTtlMinutes: {{ .Values.courseService.env.GIT_CACHE_TTL }}
    dbMaxOpenConns: {{ .Values.courseService.env.DB_MAX_OPEN_CONNS }}
    dbMaxIdleConns: {{ .Values.courseService.env.DB_MAX_IDLE_CONNS }}
    gitCredentialsPath: "/etc/git-credentials/git-credentials.yaml"
    checkerServiceUrl: "http://{{ include "pupitre.fullname" . }}-checker-service.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.checkerService.service.port }}"
