apiVersion: v2
name: pupitre
description: Pupitre Platform — Course Service (Go) + User Service (Go) + PostgreSQL + Frontend
type: application
version: 0.5.1
appVersion: "1.0.2"
keywords:
  - pupitre
  - education

annotations:
  org.opencontainers.image.source: https://github.com/genesary/pupitre-helm
  org.opencontainers.image.description: Pupitre Platform — Course Service + User Service + Frontend
