apiVersion: v2
name: elearning
description: eLearning Platform — Rust API + SvelteKit Frontend + Prometheus + Grafana
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - elearning
  - education
  - ctf
  - labs

dependencies:
  - name: postgresql
    version: "15.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
