{{- if .Values.userService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "elearning.fullname" . }}-user-service
  labels:
    {{- include "elearning.userService.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "elearning.fullname" . }}-user-service
  minReplicas: {{ .Values.userService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.userService.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.userService.autoscaling.targetCPUUtilizationPercentage }}
    {{- if .Values.userService.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.userService.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
