{{- if gt (int .Values.userService.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pupitre.fullname" . }}-user-service
  labels:
    {{- include "pupitre.userService.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "pupitre.userService.selectorLabels" . | nindent 6 }}
{{- end }}
