---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pupitre.fullname" . }}-user-service
  labels:
    {{- include "pupitre.userService.labels" . | nindent 4 }}
rules:
  - apiGroups: ["elearning.pupitre.io"]
    resources: ["markdownpatterns"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pupitre.fullname" . }}-user-service
  labels:
    {{- include "pupitre.userService.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pupitre.fullname" . }}-user-service
subjects:
  - kind: ServiceAccount
    name: {{ include "pupitre.fullname" . }}-user-service
    namespace: {{ .Release.Namespace }}
