apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elearning.fullname" . }}-user-service
  labels:
    {{- include "elearning.userService.labels" . | nindent 4 }}
automountServiceAccountToken: true
