apiVersion: v1
kind: Service
metadata:
  name: {{ include "pupitre.fullname" . }}-user-service
  labels:
    {{- include "pupitre.userService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.userService.service.type }}
  ports:
    - port: {{ .Values.userService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.userService.service.nodePort }}
      nodePort: {{ .Values.userService.service.nodePort }}
      {{- end }}
  selector:
    {{- include "pupitre.userService.selectorLabels" . | nindent 4 }}
