apiVersion: v1
kind: Service
metadata:
  name: {{ include "elearning.fullname" . }}-checker-service
  labels:
    {{- include "elearning.checkerService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.checkerService.service.type }}
  ports:
    - port: {{ .Values.checkerService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "elearning.checkerService.selectorLabels" . | nindent 4 }}
