apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elearning.fullname" . }}-frontend-config
  labels:
    {{- include "elearning.frontend.labels" . | nindent 4 }}
data:
  config.env: |
    PORT={{ .Values.frontend.service.port }}
    NODE_ENV=production
    ORIGIN={{ include "elearning.publicUrl" . }}
    PUBLIC_API_URL={{ include "elearning.publicUrl" . }}
    INTERNAL_API_URL=http://{{ include "elearning.fullname" . }}-user-service:{{ .Values.userService.service.port }}
    COURSE_API=http://{{ include "elearning.fullname" . }}-course-service:{{ .Values.courseService.service.port }}
    USER_API=http://{{ include "elearning.fullname" . }}-user-service:{{ .Values.userService.service.port }}
