apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elearning.fullname" . }}-frontend
  labels:
    {{- include "elearning.frontend.labels" . | nindent 4 }}
automountServiceAccountToken: false
