apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pupitre.fullname" . }}-frontend
  labels:
    {{- include "pupitre.frontend.labels" . | nindent 4 }}
automountServiceAccountToken: false
