apiVersion: v1
kind: Service
metadata:
  name: {{ include "pupitre.fullname" . }}-frontend
  labels:
    {{- include "pupitre.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "pupitre.name" . }}
    app.kubernetes.io/component: frontend
