apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elearning.fullname" . }}-secrets
  labels:
    {{- include "elearning.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.api.jwtSecret | quote }}
  DATABASE_URL: {{ include "elearning.databaseUrl" . | quote }}
  {{- if .Values.grafana.enabled }}
  GRAFANA_PASSWORD: {{ .Values.grafana.adminPassword | quote }}
  {{- end }}
