apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elearning.fullname" . }}-secrets
  labels:
    {{- include "elearning.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.api.jwtSecret | quote }}
  DATABASE_URL: {{ include "elearning.databaseUrl" . | quote }}
